# Generated by Django 3.1.4 on 2020-12-29 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='longitude',
            new_name='long',
        ),
    ]
